#!/bin/bash


# This should change based on language.
# lang=es or something.
# Multiple results
#URL="http://www.google.com/speech-api/v1/recognize?lang=en&client=chromium&maxresults=6"
read IDIOMA < /etc/opendomo/lang
if [ "$IDIOMA" == "es" ]  
then
	URL="https://www.google.com/speech-api/v1/recognize?lang=es_ES.utf8&client=chromium"
else
	URL="https://www.google.com/speech-api/v1/recognize?lang=en_US.utf8&client=chromium"
fi

if [ -z "$1" ];then
    echo ""
    exit 1
fi

wget -qO- --post-file "$1" --header 'Content-type: audio/x-flac; rate=8000' "$URL" > result.json

RESULT="$(cat result.json | sed 's/^[^[]*\[{\"utterance\":\"\([^\"]*\)\".*/\1/')"

echo "$RESULT"
